// oxlint-disable-next-line effecttsgo/node-builtin-import -- This diagnostic hashes generated bytes incrementally without buffering a long master.
import { createHash } from "node:crypto";

import { Effect, Option, Schema, Stream } from "effect";

import { AsrProbeLanguage, storedByteHash, validateDocument } from "@trigo/contracts";

import {
  AsrExtractionError,
  AsrMaster,
  AsrSubmissionInterval,
  asrReadRangeBytes,
  makeAsrMasterHeader,
  planMasterSubmissions,
} from "./asr-master.ts";

const fixtureBlockMs = 20_000;
const fixtureBlockBytes = fixtureBlockMs * 64;
export const fixtureTemplateByteLength = 68 + 3 * fixtureBlockBytes;

export const HostedMasterFixture = Schema.Struct({
  schemaVersion: Schema.Literal(1),
  fixture: Schema.String.check(Schema.isPattern(/^[a-z0-9][a-z0-9-]{0,79}$/)),
  language: AsrProbeLanguage,
  createdAt: Schema.NonEmptyString,
  revisionId: AsrMaster.fields.callId,
  templateSha256: AsrMaster.fields.sha256,
  templateLayout: Schema.Literal("twenty-second-blocks-start-middle-final-v1"),
  master: AsrMaster,
  intervals: Schema.Array(AsrSubmissionInterval),
  manifestText: Schema.String,
});
export interface HostedMasterFixture extends Schema.Schema.Type<typeof HostedMasterFixture> {}

/** Repetition supplies background speech; unique middle/final blocks expose wrong range offsets. */
export const controlledMasterStream = (
  template: Uint8Array,
  durationMs: number,
): Stream.Stream<Uint8Array, AsrExtractionError> =>
  Stream.unwrap(
    Effect.gen(function* () {
      const header = makeAsrMasterHeader();
      if (
        template.byteLength !== fixtureTemplateByteLength ||
        header.some((byte, index) => template[index] !== byte) ||
        !Number.isSafeInteger(durationMs) ||
        durationMs < 60_000 ||
        durationMs > 10_800_000 ||
        durationMs % fixtureBlockMs !== 0
      ) {
        return yield* new AsrExtractionError({
          operation: "fixture",
          message:
            "Use the controlled 60-second CAF template and a whole 20-second duration from one minute through three hours",
        });
      }
      const blocks = durationMs / fixtureBlockMs;
      const middle = Math.floor(blocks / 2);
      const totalBytes = durationMs * 64;
      const pcm = Stream.paginate(0, (offset) =>
        Effect.sync(() => {
          const block = Math.floor(offset / fixtureBlockBytes);
          let templateBlock = 0;
          if (block === middle) {
            templateBlock = 1;
          }
          if (block === blocks - 1) {
            templateBlock = 2;
          }
          const inBlock = offset % fixtureBlockBytes;
          const length = Math.min(
            asrReadRangeBytes,
            fixtureBlockBytes - inBlock,
            totalBytes - offset,
          );
          const start = 68 + templateBlock * fixtureBlockBytes + inBlock;
          const next = offset + length;
          return [
            [template.subarray(start, start + length)],
            next === totalBytes ? Option.none() : Option.some(next),
          ] as const;
        }),
      );
      return Stream.concat(Stream.make(header), pcm);
    }),
  );

export const prepareHostedMasterFixture = Effect.fn("HostedMasterFixture.prepare")(function* (
  fixture: string,
  language: AsrProbeLanguage,
  template: Uint8Array,
  durationMs: number,
  intervalMs: number,
  createdAt: string,
  makeId: () => string,
) {
  const digest = createHash("sha256");
  yield* controlledMasterStream(template, durationMs).pipe(
    Stream.runForEach((chunk) =>
      Effect.sync(() => {
        digest.update(chunk);
      }),
    ),
  );
  const callId = makeId();
  const masterId = makeId();
  const manifestId = makeId();
  const microphoneTrackId = makeId();
  const applicationTrackId = makeId();
  const masterSha256 = digest.digest("hex");
  const manifest = yield* Effect.try({
    try: () =>
      validateDocument("AudioManifest", {
        schemaVersion: 1,
        callId,
        manifestId,
        durationMs,
        mediaProfileId: "caf-lpcm-s16le-16000-stereo-v1",
        objects: [
          {
            objectId: masterId,
            index: 0,
            contentType: "audio/x-caf",
            byteLength: 68 + durationMs * 64,
            sha256: masterSha256,
            startMs: 0,
            endMs: durationMs,
            channelMap: [
              { channelIndex: 0, trackId: microphoneTrackId },
              { channelIndex: 1, trackId: applicationTrackId },
            ],
          },
        ],
      }),
    catch: () =>
      new AsrExtractionError({
        operation: "fixture",
        message: "Generated master manifest is invalid",
      }),
  });
  const manifestText = yield* Schema.encodeEffect(Schema.fromJsonString(Schema.Unknown))(
    manifest,
  ).pipe(
    Effect.mapError(
      () =>
        new AsrExtractionError({
          operation: "fixture",
          message: "Generated manifest cannot be encoded",
        }),
    ),
  );
  const master = AsrMaster.make({
    callId,
    masterId,
    manifestId,
    manifestSha256: yield* Effect.promise(() =>
      storedByteHash(new TextEncoder().encode(manifestText)),
    ),
    sha256: masterSha256,
    frameCount: durationMs * 16,
    byteLength: 68 + durationMs * 64,
    mediaProfileId: "caf-lpcm-s16le-16000-stereo-v1",
    microphoneTrackId,
    applicationTrackId,
  });
  const intervals = yield* planMasterSubmissions(master, intervalMs, makeId);
  return HostedMasterFixture.make({
    schemaVersion: 1,
    fixture,
    language,
    createdAt,
    revisionId: makeId(),
    templateSha256: yield* Effect.promise(() => storedByteHash(template)),
    templateLayout: "twenty-second-blocks-start-middle-final-v1",
    master,
    intervals,
    manifestText,
  });
});

/** FixedLengthStream gives R2 a known length while retaining a bounded producer. */
export const storeControlledMaster = Effect.fn("HostedMasterFixture.store")(function* (
  bucket: Pick<R2Bucket, "put">,
  objectKey: string,
  template: Uint8Array,
  fixture: HostedMasterFixture,
) {
  const fixed = new FixedLengthStream(fixture.master.byteLength);
  const readable = yield* Stream.toReadableStreamEffect(
    controlledMasterStream(template, fixture.master.frameCount / 16),
  );
  const producer = Effect.tryPromise({
    try: (signal) => readable.pipeTo(fixed.writable, { signal }),
    catch: () =>
      new AsrExtractionError({
        operation: "fixture",
        message: "Controlled master generation did not complete",
      }),
  });
  const store = Effect.tryPromise({
    try: () =>
      bucket.put(objectKey, fixed.readable, {
        onlyIf: { etagDoesNotMatch: "*" },
        sha256: fixture.master.sha256,
        httpMetadata: { contentType: "audio/x-caf" },
        customMetadata: {
          sha256: fixture.master.sha256,
          mediaProfileId: fixture.master.mediaProfileId,
        },
      }),
    catch: () =>
      new AsrExtractionError({ operation: "fixture", message: "Controlled master storage failed" }),
  }).pipe(
    Effect.filterOrFail(
      (object) => object !== null,
      () =>
        new AsrExtractionError({
          operation: "fixture",
          message: "Controlled master identity already exists",
        }),
    ),
  );
  yield* Effect.all([producer, store], { concurrency: "unbounded" });
});
